In [ ]:
!pip install transformers

In [ ]:
from transformers import AutoTokenizer

In [ ]:
checkpoint="bert-base-uncased"
tokenizer=AutoTokenizer.from_pretrained(checkpoint)

In [ ]:
tokenizer

BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True)

In [ ]:
tokenizer("Hello world")

{'input_ids': [101, 7592, 2088, 102], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [ ]:
tokens=tokenizer.tokenize("hello world")
tokens

['hello', 'world']

In [ ]:
ids=tokenizer.convert_tokens_to_ids(tokens)
ids

[7592, 2088]

In [ ]:
tokenizer.convert_ids_to_tokens(ids)

['hello', 'world']

In [ ]:
tokenizer.decode(ids)

'hello world'

In [ ]:
ids=tokenizer.encode("hello world")
ids

[101, 7592, 2088, 102]

In [ ]:
tokenizer.convert_ids_to_tokens(ids)

['[CLS]', 'hello', 'world', '[SEP]']

In [ ]:
tokenizer.decode(ids)

'[CLS] hello world [SEP]'

In [ ]:
model_inputs=tokenizer("hello world")
model_inputs

{'input_ids': [101, 7592, 2088, 102], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [ ]:
data=[
    "I like cats.",
    "Do you like cats too?"
]
tokenizer(data)

{'input_ids': [[101, 1045, 2066, 8870, 1012, 102], [101, 2079, 2017, 2066, 8870, 2205, 1029, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]}

In [ ]:
from transformers import AutoModelForSequenceClassification

In [ ]:
model=AutoModelForSequenceClassification.from_pretrained(checkpoint)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
outputs=model(**model_inputs)

AttributeError: ignored

In [ ]:
model_inputs=tokenizer("hello world",return_tensors='pt')
model_inputs

{'input_ids': tensor([[ 101, 7592, 2088,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [ ]:
# the default was to create a binary classifier
outputs=model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.9666, -0.2976]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
model=AutoModelForSequenceClassification.from_pretrained(checkpoint,num_labels=3)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
outputs=model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.1843, -0.1466,  0.2405]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
outputs.logits

tensor([[ 0.1843, -0.1466,  0.2405]], grad_fn=<AddmmBackward0>)

In [ ]:
outputs['logits']

tensor([[ 0.1843, -0.1466,  0.2405]], grad_fn=<AddmmBackward0>)

In [ ]:
outputs[0]

tensor([[ 0.1843, -0.1466,  0.2405]], grad_fn=<AddmmBackward0>)

In [ ]:
outputs.logits.detach().cpu().numpy()

array([[ 0.18427415, -0.14658296,  0.2404745 ]], dtype=float32)

In [ ]:
data=[
    "I like cats.",
    "Do you like cats too?",

]
model_inputs=tokenizer(data,return_tensors='pt')
model_inputs

ValueError: ignored

In [ ]:
model_inputs=tokenizer(
    data,padding=True,truncation=True,return_tensors='pt')
model_inputs

{'input_ids': tensor([[ 101, 1045, 2066, 8870, 1012,  102,    0,    0],
        [ 101, 2079, 2017, 2066, 8870, 2205, 1029,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
model_inputs['input_ids']

tensor([[ 101, 1045, 2066, 8870, 1012,  102,    0,    0],
        [ 101, 2079, 2017, 2066, 8870, 2205, 1029,  102]])

In [ ]:
model_inputs['attention_mask']

tensor([[1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
output=model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.1843, -0.1466,  0.2405]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)